name: Docker Compose Down

on:
  workflow_dispatch:

jobs:
  composer-down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker compose down
        run: docker compose down